<?php
/**
 * @category   Custom
 * @package    Custom_FormData
 * @author     shambhusinghdce@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Custom\FormData\Model\ResourceModel;

class FormData extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('custom_formdata', 'formdata_id');   //here "custom_formdata" is table name and "formdata_id" is the primary key of custom table
    }
}